name: magnus_flutter_kelvin_prayitno
description: Magnus Project Challenge by Kelvin Prayitno

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # networking
  dio: ^5.2.0
  cached_network_image: ^3.2.3
  html: ^0.15.1

  # state management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # model
  json_annotation: ^4.8.1

  #  DI
  get_it: ^7.6.0
  injectable: ^2.1.1

  #UI
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  intl: ^0.18.0
  intl_utils: ^2.8.3
  mocktail: ^1.0.3
  touchable_opacity: ^1.2.0

  #Storage
  flutter_secure_storage: ^9.0.0
  floor: ^1.4.2
  sqflite: ^2.3.2
  url_launcher: ^6.1.14
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  path_provider: ^2.1.2
  flutter_timezone: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # unit test
  mockito: ^5.4.2
  build_runner: ^2.1.11

  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.5
  flutter_launcher_icons: ^0.10.0
  json_serializable: ^6.3.1
  bloc_test: ^9.1.3
  floor_generator: ^1.4.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_intl:
  enabled: true

flutter_icons:
  image_path: "assets/images/ic_swapi_movie.png"
  android: true
  ios: true
