var movieRawResponse = '''
    {
    "count": 6,
    "next": null,
    "previous": null,
    "results": [
        {
            "title": "A New Hope",
            "episode_id": 4,
            "opening_crawl": "It is a period of civil war.Rebel spaceships, strikingfrom a hidden base, have wontheir first victory againstthe evil Galactic Empire.During the battle, Rebelspies managed to steal secretplans to the Empire'sultimate weapon, the DEATHSTAR, an armored spacestation with enough powerto destroy an entire planet.Pursued by the Empire'ssinister agents, PrincessLeia races home aboard herstarship, custodian of thestolen plans that can save herpeople and restorefreedom to the galaxy....",
            "director": "George Lucas",
            "producer": "Gary Kurtz, Rick McCallum",
            "release_date": "1977-05-25",
            "characters": [
                "https://swapi.dev/api/people/1/",
                "https://swapi.dev/api/people/2/",
                "https://swapi.dev/api/people/3/",
                "https://swapi.dev/api/people/4/",
                "https://swapi.dev/api/people/5/",
                "https://swapi.dev/api/people/6/",
                "https://swapi.dev/api/people/7/",
                "https://swapi.dev/api/people/8/",
                "https://swapi.dev/api/people/9/",
                "https://swapi.dev/api/people/10/",
                "https://swapi.dev/api/people/12/",
                "https://swapi.dev/api/people/13/",
                "https://swapi.dev/api/people/14/",
                "https://swapi.dev/api/people/15/",
                "https://swapi.dev/api/people/16/",
                "https://swapi.dev/api/people/18/",
                "https://swapi.dev/api/people/19/",
                "https://swapi.dev/api/people/81/"
            ],
            "planets": [
                "https://swapi.dev/api/planets/1/",
                "https://swapi.dev/api/planets/2/",
                "https://swapi.dev/api/planets/3/"
            ],
            "starships": [
                "https://swapi.dev/api/starships/2/",
                "https://swapi.dev/api/starships/3/",
                "https://swapi.dev/api/starships/5/",
                "https://swapi.dev/api/starships/9/",
                "https://swapi.dev/api/starships/10/",
                "https://swapi.dev/api/starships/11/",
                "https://swapi.dev/api/starships/12/",
                "https://swapi.dev/api/starships/13/"
            ],
            "vehicles": [
                "https://swapi.dev/api/vehicles/4/",
                "https://swapi.dev/api/vehicles/6/",
                "https://swapi.dev/api/vehicles/7/",
                "https://swapi.dev/api/vehicles/8/"
            ],
            "species": [
                "https://swapi.dev/api/species/1/",
                "https://swapi.dev/api/species/2/",
                "https://swapi.dev/api/species/3/",
                "https://swapi.dev/api/species/4/",
                "https://swapi.dev/api/species/5/"
            ],
            "created": "2014-12-10T14:23:31.880000Z",
            "edited": "2014-12-20T19:49:45.256000Z",
            "url": "https://swapi.dev/api/films/1/"
        },
        {
            "title": "The Empire Strikes Back",
            "episode_id": 5,
            "opening_crawl": "It is a dark time for theRebellion. Although the DeathStar has been destroyed,Imperial troops have driven theRebel forces from their hiddenbase and pursued them acrossthe galaxy.Evading the dreaded ImperialStarfleet, a group of freedomfighters led by Luke Skywalkerhas established a new secretbase on the remote ice worldof Hoth.The evil lord Darth Vader,obsessed with finding youngSkywalker, has dispatchedthousands of remote probes intothe far reaches of space....",
            "director": "Irvin Kershner",
            "producer": "Gary Kurtz, Rick McCallum",
            "release_date": "1980-05-17",
            "characters": [
                "https://swapi.dev/api/people/1/",
                "https://swapi.dev/api/people/2/",
                "https://swapi.dev/api/people/3/",
                "https://swapi.dev/api/people/4/",
                "https://swapi.dev/api/people/5/",
                "https://swapi.dev/api/people/10/",
                "https://swapi.dev/api/people/13/",
                "https://swapi.dev/api/people/14/",
                "https://swapi.dev/api/people/18/",
                "https://swapi.dev/api/people/20/",
                "https://swapi.dev/api/people/21/",
                "https://swapi.dev/api/people/22/",
                "https://swapi.dev/api/people/23/",
                "https://swapi.dev/api/people/24/",
                "https://swapi.dev/api/people/25/",
                "https://swapi.dev/api/people/26/"
            ],
            "planets": [
                "https://swapi.dev/api/planets/4/",
                "https://swapi.dev/api/planets/5/",
                "https://swapi.dev/api/planets/6/",
                "https://swapi.dev/api/planets/27/"
            ],
            "starships": [
                "https://swapi.dev/api/starships/3/",
                "https://swapi.dev/api/starships/10/",
                "https://swapi.dev/api/starships/11/",
                "https://swapi.dev/api/starships/12/",
                "https://swapi.dev/api/starships/15/",
                "https://swapi.dev/api/starships/17/",
                "https://swapi.dev/api/starships/21/",
                "https://swapi.dev/api/starships/22/",
                "https://swapi.dev/api/starships/23/"
            ],
            "vehicles": [
                "https://swapi.dev/api/vehicles/8/",
                "https://swapi.dev/api/vehicles/14/",
                "https://swapi.dev/api/vehicles/16/",
                "https://swapi.dev/api/vehicles/18/",
                "https://swapi.dev/api/vehicles/19/",
                "https://swapi.dev/api/vehicles/20/"
            ],
            "species": [
                "https://swapi.dev/api/species/1/",
                "https://swapi.dev/api/species/2/",
                "https://swapi.dev/api/species/3/",
                "https://swapi.dev/api/species/6/",
                "https://swapi.dev/api/species/7/"
            ],
            "created": "2014-12-12T11:26:24.656000Z",
            "edited": "2014-12-15T13:07:53.386000Z",
            "url": "https://swapi.dev/api/films/2/"
        },
        {
            "title": "Return of the Jedi",
            "episode_id": 6,
            "opening_crawl": "Luke Skywalker has returned tohis home planet of Tatooine inan attempt to rescue hisfriend Han Solo from theclutches of the vile gangsterJabba the Hutt.Little does Luke know that theGALACTIC EMPIRE has secretlybegun construction on a newarmored space station evenmore powerful than the firstdreaded Death Star.When completed, this ultimateweapon will spell certain doomfor the small band of rebelsstruggling to restore freedomto the galaxy...",
            "director": "Richard Marquand",
            "producer": "Howard G. Kazanjian, George Lucas, Rick McCallum",
            "release_date": "1983-05-25",
            "characters": [
                "https://swapi.dev/api/people/1/",
                "https://swapi.dev/api/people/2/",
                "https://swapi.dev/api/people/3/",
                "https://swapi.dev/api/people/4/",
                "https://swapi.dev/api/people/5/",
                "https://swapi.dev/api/people/10/",
                "https://swapi.dev/api/people/13/",
                "https://swapi.dev/api/people/14/",
                "https://swapi.dev/api/people/16/",
                "https://swapi.dev/api/people/18/",
                "https://swapi.dev/api/people/20/",
                "https://swapi.dev/api/people/21/",
                "https://swapi.dev/api/people/22/",
                "https://swapi.dev/api/people/25/",
                "https://swapi.dev/api/people/27/",
                "https://swapi.dev/api/people/28/",
                "https://swapi.dev/api/people/29/",
                "https://swapi.dev/api/people/30/",
                "https://swapi.dev/api/people/31/",
                "https://swapi.dev/api/people/45/"
            ],
            "planets": [
                "https://swapi.dev/api/planets/1/",
                "https://swapi.dev/api/planets/5/",
                "https://swapi.dev/api/planets/7/",
                "https://swapi.dev/api/planets/8/",
                "https://swapi.dev/api/planets/9/"
            ],
            "starships": [
                "https://swapi.dev/api/starships/2/",
                "https://swapi.dev/api/starships/3/",
                "https://swapi.dev/api/starships/10/",
                "https://swapi.dev/api/starships/11/",
                "https://swapi.dev/api/starships/12/",
                "https://swapi.dev/api/starships/15/",
                "https://swapi.dev/api/starships/17/",
                "https://swapi.dev/api/starships/22/",
                "https://swapi.dev/api/starships/23/",
                "https://swapi.dev/api/starships/27/",
                "https://swapi.dev/api/starships/28/",
                "https://swapi.dev/api/starships/29/"
            ],
            "vehicles": [
                "https://swapi.dev/api/vehicles/8/",
                "https://swapi.dev/api/vehicles/16/",
                "https://swapi.dev/api/vehicles/18/",
                "https://swapi.dev/api/vehicles/19/",
                "https://swapi.dev/api/vehicles/24/",
                "https://swapi.dev/api/vehicles/25/",
                "https://swapi.dev/api/vehicles/26/",
                "https://swapi.dev/api/vehicles/30/"
            ],
            "species": [
                "https://swapi.dev/api/species/1/",
                "https://swapi.dev/api/species/2/",
                "https://swapi.dev/api/species/3/",
                "https://swapi.dev/api/species/5/",
                "https://swapi.dev/api/species/6/",
                "https://swapi.dev/api/species/8/",
                "https://swapi.dev/api/species/9/",
                "https://swapi.dev/api/species/10/",
                "https://swapi.dev/api/species/15/"
            ],
            "created": "2014-12-18T10:39:33.255000Z",
            "edited": "2014-12-20T09:48:37.462000Z",
            "url": "https://swapi.dev/api/films/3/"
        },
        {
            "title": "The Phantom Menace",
            "episode_id": 1,
            "opening_crawl": "Turmoil has engulfed theGalactic Republic. The taxationof trade routes to outlying starsystems is in dispute.Hoping to resolve the matterwith a blockade of deadlybattleships, the greedy TradeFederation has stopped allshipping to the small planetof Naboo.While the Congress of theRepublic endlessly debatesthis alarming chain of events,the Supreme Chancellor hassecretly dispatched two JediKnights, the guardians ofpeace and justice in thegalaxy, to settle the conflict....",
            "director": "George Lucas",
            "producer": "Rick McCallum",
            "release_date": "1999-05-19",
            "characters": [
                "https://swapi.dev/api/people/2/",
                "https://swapi.dev/api/people/3/",
                "https://swapi.dev/api/people/10/",
                "https://swapi.dev/api/people/11/",
                "https://swapi.dev/api/people/16/",
                "https://swapi.dev/api/people/20/",
                "https://swapi.dev/api/people/21/",
                "https://swapi.dev/api/people/32/",
                "https://swapi.dev/api/people/33/",
                "https://swapi.dev/api/people/34/",
                "https://swapi.dev/api/people/35/",
                "https://swapi.dev/api/people/36/",
                "https://swapi.dev/api/people/37/",
                "https://swapi.dev/api/people/38/",
                "https://swapi.dev/api/people/39/",
                "https://swapi.dev/api/people/40/",
                "https://swapi.dev/api/people/41/",
                "https://swapi.dev/api/people/42/",
                "https://swapi.dev/api/people/43/",
                "https://swapi.dev/api/people/44/",
                "https://swapi.dev/api/people/46/",
                "https://swapi.dev/api/people/47/",
                "https://swapi.dev/api/people/48/",
                "https://swapi.dev/api/people/49/",
                "https://swapi.dev/api/people/50/",
                "https://swapi.dev/api/people/51/",
                "https://swapi.dev/api/people/52/",
                "https://swapi.dev/api/people/53/",
                "https://swapi.dev/api/people/54/",
                "https://swapi.dev/api/people/55/",
                "https://swapi.dev/api/people/56/",
                "https://swapi.dev/api/people/57/",
                "https://swapi.dev/api/people/58/",
                "https://swapi.dev/api/people/59/"
            ],
            "planets": [
                "https://swapi.dev/api/planets/1/",
                "https://swapi.dev/api/planets/8/",
                "https://swapi.dev/api/planets/9/"
            ],
            "starships": [
                "https://swapi.dev/api/starships/31/",
                "https://swapi.dev/api/starships/32/",
                "https://swapi.dev/api/starships/39/",
                "https://swapi.dev/api/starships/40/",
                "https://swapi.dev/api/starships/41/"
            ],
            "vehicles": [
                "https://swapi.dev/api/vehicles/33/",
                "https://swapi.dev/api/vehicles/34/",
                "https://swapi.dev/api/vehicles/35/",
                "https://swapi.dev/api/vehicles/36/",
                "https://swapi.dev/api/vehicles/37/",
                "https://swapi.dev/api/vehicles/38/",
                "https://swapi.dev/api/vehicles/42/"
            ],
            "species": [
                "https://swapi.dev/api/species/1/",
                "https://swapi.dev/api/species/2/",
                "https://swapi.dev/api/species/6/",
                "https://swapi.dev/api/species/11/",
                "https://swapi.dev/api/species/12/",
                "https://swapi.dev/api/species/13/",
                "https://swapi.dev/api/species/14/",
                "https://swapi.dev/api/species/15/",
                "https://swapi.dev/api/species/16/",
                "https://swapi.dev/api/species/17/",
                "https://swapi.dev/api/species/18/",
                "https://swapi.dev/api/species/19/",
                "https://swapi.dev/api/species/20/",
                "https://swapi.dev/api/species/21/",
                "https://swapi.dev/api/species/22/",
                "https://swapi.dev/api/species/23/",
                "https://swapi.dev/api/species/24/",
                "https://swapi.dev/api/species/25/",
                "https://swapi.dev/api/species/26/",
                "https://swapi.dev/api/species/27/"
            ],
            "created": "2014-12-19T16:52:55.740000Z",
            "edited": "2014-12-20T10:54:07.216000Z",
            "url": "https://swapi.dev/api/films/4/"
        },
        {
            "title": "Attack of the Clones",
            "episode_id": 2,
            "opening_crawl": "There is unrest in the GalacticSenate. Several thousand solarsystems have declared theirintentions to leave the Republic.This separatist movement,under the leadership of themysterious Count Dooku, hasmade it difficult for the limitednumber of Jedi Knights to maintain peace and order in the galaxy.Senator Amidala, the formerQueen of Naboo, is returningto the Galactic Senate to voteon the critical issue of creatingan ARMY OF THE REPUBLICto assist the overwhelmedJedi....",
            "director": "George Lucas",
            "producer": "Rick McCallum",
            "release_date": "2002-05-16",
            "characters": [
                "https://swapi.dev/api/people/2/",
                "https://swapi.dev/api/people/3/",
                "https://swapi.dev/api/people/6/",
                "https://swapi.dev/api/people/7/",
                "https://swapi.dev/api/people/10/",
                "https://swapi.dev/api/people/11/",
                "https://swapi.dev/api/people/20/",
                "https://swapi.dev/api/people/21/",
                "https://swapi.dev/api/people/22/",
                "https://swapi.dev/api/people/33/",
                "https://swapi.dev/api/people/35/",
                "https://swapi.dev/api/people/36/",
                "https://swapi.dev/api/people/40/",
                "https://swapi.dev/api/people/43/",
                "https://swapi.dev/api/people/46/",
                "https://swapi.dev/api/people/51/",
                "https://swapi.dev/api/people/52/",
                "https://swapi.dev/api/people/53/",
                "https://swapi.dev/api/people/58/",
                "https://swapi.dev/api/people/59/",
                "https://swapi.dev/api/people/60/",
                "https://swapi.dev/api/people/61/",
                "https://swapi.dev/api/people/62/",
                "https://swapi.dev/api/people/63/",
                "https://swapi.dev/api/people/64/",
                "https://swapi.dev/api/people/65/",
                "https://swapi.dev/api/people/66/",
                "https://swapi.dev/api/people/67/",
                "https://swapi.dev/api/people/68/",
                "https://swapi.dev/api/people/69/",
                "https://swapi.dev/api/people/70/",
                "https://swapi.dev/api/people/71/",
                "https://swapi.dev/api/people/72/",
                "https://swapi.dev/api/people/73/",
                "https://swapi.dev/api/people/74/",
                "https://swapi.dev/api/people/75/",
                "https://swapi.dev/api/people/76/",
                "https://swapi.dev/api/people/77/",
                "https://swapi.dev/api/people/78/",
                "https://swapi.dev/api/people/82/"
            ],
            "planets": [
                "https://swapi.dev/api/planets/1/",
                "https://swapi.dev/api/planets/8/",
                "https://swapi.dev/api/planets/9/",
                "https://swapi.dev/api/planets/10/",
                "https://swapi.dev/api/planets/11/"
            ],
            "starships": [
                "https://swapi.dev/api/starships/21/",
                "https://swapi.dev/api/starships/32/",
                "https://swapi.dev/api/starships/39/",
                "https://swapi.dev/api/starships/43/",
                "https://swapi.dev/api/starships/47/",
                "https://swapi.dev/api/starships/48/",
                "https://swapi.dev/api/starships/49/",
                "https://swapi.dev/api/starships/52/",
                "https://swapi.dev/api/starships/58/"
            ],
            "vehicles": [
                "https://swapi.dev/api/vehicles/4/",
                "https://swapi.dev/api/vehicles/44/",
                "https://swapi.dev/api/vehicles/45/",
                "https://swapi.dev/api/vehicles/46/",
                "https://swapi.dev/api/vehicles/50/",
                "https://swapi.dev/api/vehicles/51/",
                "https://swapi.dev/api/vehicles/53/",
                "https://swapi.dev/api/vehicles/54/",
                "https://swapi.dev/api/vehicles/55/",
                "https://swapi.dev/api/vehicles/56/",
                "https://swapi.dev/api/vehicles/57/"
            ],
            "species": [
                "https://swapi.dev/api/species/1/",
                "https://swapi.dev/api/species/2/",
                "https://swapi.dev/api/species/6/",
                "https://swapi.dev/api/species/12/",
                "https://swapi.dev/api/species/13/",
                "https://swapi.dev/api/species/15/",
                "https://swapi.dev/api/species/28/",
                "https://swapi.dev/api/species/29/",
                "https://swapi.dev/api/species/30/",
                "https://swapi.dev/api/species/31/",
                "https://swapi.dev/api/species/32/",
                "https://swapi.dev/api/species/33/",
                "https://swapi.dev/api/species/34/",
                "https://swapi.dev/api/species/35/"
            ],
            "created": "2014-12-20T10:57:57.886000Z",
            "edited": "2014-12-20T20:18:48.516000Z",
            "url": "https://swapi.dev/api/films/5/"
        },
        {
            "title": "Revenge of the Sith",
            "episode_id": 3,
            "opening_crawl": "War! The Republic is crumblingunder attacks by the ruthlessSith Lord, Count Dooku.There are heroes on both sides.Evil is everywhere.In a stunning move, thefiendish droid leader, GeneralGrievous, has swept into theRepublic capital and kidnappedChancellor Palpatine, leader ofthe Galactic Senate.As the Separatist Droid Armyattempts to flee the besiegedcapital with their valuablehostage, two Jedi Knights lead adesperate mission to rescue thecaptive Chancellor....",
            "director": "George Lucas",
            "producer": "Rick McCallum",
            "release_date": "2005-05-19",
            "characters": [
                "https://swapi.dev/api/people/1/",
                "https://swapi.dev/api/people/2/",
                "https://swapi.dev/api/people/3/",
                "https://swapi.dev/api/people/4/",
                "https://swapi.dev/api/people/5/",
                "https://swapi.dev/api/people/6/",
                "https://swapi.dev/api/people/7/",
                "https://swapi.dev/api/people/10/",
                "https://swapi.dev/api/people/11/",
                "https://swapi.dev/api/people/12/",
                "https://swapi.dev/api/people/13/",
                "https://swapi.dev/api/people/20/",
                "https://swapi.dev/api/people/21/",
                "https://swapi.dev/api/people/33/",
                "https://swapi.dev/api/people/35/",
                "https://swapi.dev/api/people/46/",
                "https://swapi.dev/api/people/51/",
                "https://swapi.dev/api/people/52/",
                "https://swapi.dev/api/people/53/",
                "https://swapi.dev/api/people/54/",
                "https://swapi.dev/api/people/55/",
                "https://swapi.dev/api/people/56/",
                "https://swapi.dev/api/people/58/",
                "https://swapi.dev/api/people/63/",
                "https://swapi.dev/api/people/64/",
                "https://swapi.dev/api/people/67/",
                "https://swapi.dev/api/people/68/",
                "https://swapi.dev/api/people/75/",
                "https://swapi.dev/api/people/78/",
                "https://swapi.dev/api/people/79/",
                "https://swapi.dev/api/people/80/",
                "https://swapi.dev/api/people/81/",
                "https://swapi.dev/api/people/82/",
                "https://swapi.dev/api/people/83/"
            ],
            "planets": [
                "https://swapi.dev/api/planets/1/",
                "https://swapi.dev/api/planets/2/",
                "https://swapi.dev/api/planets/5/",
                "https://swapi.dev/api/planets/8/",
                "https://swapi.dev/api/planets/9/",
                "https://swapi.dev/api/planets/12/",
                "https://swapi.dev/api/planets/13/",
                "https://swapi.dev/api/planets/14/",
                "https://swapi.dev/api/planets/15/",
                "https://swapi.dev/api/planets/16/",
                "https://swapi.dev/api/planets/17/",
                "https://swapi.dev/api/planets/18/",
                "https://swapi.dev/api/planets/19/"
            ],
            "starships": [
                "https://swapi.dev/api/starships/2/",
                "https://swapi.dev/api/starships/32/",
                "https://swapi.dev/api/starships/48/",
                "https://swapi.dev/api/starships/59/",
                "https://swapi.dev/api/starships/61/",
                "https://swapi.dev/api/starships/63/",
                "https://swapi.dev/api/starships/64/",
                "https://swapi.dev/api/starships/65/",
                "https://swapi.dev/api/starships/66/",
                "https://swapi.dev/api/starships/68/",
                "https://swapi.dev/api/starships/74/",
                "https://swapi.dev/api/starships/75/"
            ],
            "vehicles": [
                "https://swapi.dev/api/vehicles/33/",
                "https://swapi.dev/api/vehicles/50/",
                "https://swapi.dev/api/vehicles/53/",
                "https://swapi.dev/api/vehicles/56/",
                "https://swapi.dev/api/vehicles/60/",
                "https://swapi.dev/api/vehicles/62/",
                "https://swapi.dev/api/vehicles/67/",
                "https://swapi.dev/api/vehicles/69/",
                "https://swapi.dev/api/vehicles/70/",
                "https://swapi.dev/api/vehicles/71/",
                "https://swapi.dev/api/vehicles/72/",
                "https://swapi.dev/api/vehicles/73/",
                "https://swapi.dev/api/vehicles/76/"
            ],
            "species": [
                "https://swapi.dev/api/species/1/",
                "https://swapi.dev/api/species/2/",
                "https://swapi.dev/api/species/3/",
                "https://swapi.dev/api/species/6/",
                "https://swapi.dev/api/species/15/",
                "https://swapi.dev/api/species/19/",
                "https://swapi.dev/api/species/20/",
                "https://swapi.dev/api/species/23/",
                "https://swapi.dev/api/species/24/",
                "https://swapi.dev/api/species/25/",
                "https://swapi.dev/api/species/26/",
                "https://swapi.dev/api/species/27/",
                "https://swapi.dev/api/species/28/",
                "https://swapi.dev/api/species/29/",
                "https://swapi.dev/api/species/30/",
                "https://swapi.dev/api/species/33/",
                "https://swapi.dev/api/species/34/",
                "https://swapi.dev/api/species/35/",
                "https://swapi.dev/api/species/36/",
                "https://swapi.dev/api/species/37/"
            ],
            "created": "2014-12-20T18:49:38.403000Z",
            "edited": "2014-12-20T20:47:52.073000Z",
            "url": "https://swapi.dev/api/films/6/"
        }
    ]
}
    ''';

var movieEmptyArticleRawResponse = '''
    {
    "status": "ok",
    "totalResults": 0,
    "articles": []
}
    ''';

var movieErrorRaw = '''
{
    "status": "error",
    "code": "parametersMissing",
    "message": "Required parameters are missing, the scope of your search is too broad. Please set any of the following required parameters and try again: q, qInTitle, sources, domains."
}
''';
